import tcs from '../../../assest/tcs.jpeg';
import reliance from '../../../assest/reliance.jpeg';
import hdfc from '../../../assest/hdfc.jpeg';

export const screenerStockListData = [
    {
      symbol: "RELIANCE INDUSTRIES LTD",
      price: "₹1,272.15",
      change: "-0.09%",
      volume: "3.65 M",
      marketCap: "₹17.23T",
      pToE: "25.35",
      eps: "₹50.19",
      epsDilGrowth: "-0.85%",
      divYield: "0.39%",
      sector: "Energy minerals",
      icon:  reliance, // Add the image path or URL
    },
    {
      symbol: "TATA CONSULTANCY SERVICES LTD",
      price: "₹4,442.80",
      change: "-0.69%",
      volume: "7.62 K",
      marketCap: "₹16.19T",
      pToE: "33.95",
      eps: "₹130.85",
      epsDilGrowth: "+7.22%",
      divYield: "1.27%",
      sector: "Technology services",
      icon: tcs, // Use the imported variable
    },
    {
      symbol: "HDFC BANK LTD",
      price: "₹1,862.75",
      change: "-0.48%",
      volume: "2.46 M",
      marketCap: "₹14.31T",
      pToE: "25.55",
      eps: "₹90.65",
      epsDilGrowth: "+1.52%",
      divYield: "1.04%",
      sector: "Finance",
      icon: hdfc, // Add more logos
    },
    // Add more companies as needed
    {
        symbol: "BHARTI AIRTEL LTD",
        price: "₹1,644.40",
        change: "-1.03%",
        volume: "2.27 M",
        marketCap: "₹9.57T",
        eps: "₹20.24",
        epsDilGrowth: "+60.69%",
        divYield: "0.48%",
        sector: "Communications",
        icon: "path/to/bharti-airtel-logo.png",
      },
      {
        symbol: "ICICI BANK LTD",
        price: "₹1,345.35",
        change: "+0.03%",
        volume: "3.55 M",
        marketCap: "₹9.43T",
        eps: "₹66.16",
        epsDilGrowth: "+17.37%",
        divYield: "0.74%",
        sector: "Finance",
        icon: "path/to/icici-logo.png",
      },
      {
        symbol: "INFOSYS LTD",
        price: "₹1,990.50",
        change: "-0.46%",
        volume: "793.91 K",
        marketCap: "₹8.30T",
        eps: "₹64.99",
        epsDilGrowth: "+8.66%",
        divYield: "2.05%",
        sector: "Technology services",
        icon: "path/to/infosys-logo.png",
      },
      {
        symbol: "STATE BANK OF INDIA",
        price: "₹861.95",
        change: "+0.52%",
        volume: "2.52 M",
        marketCap: "₹5.91T",
        eps: "₹10.73",
        epsDilGrowth: "+4.91%",
        divYield: "1.59%",
        sector: "Finance",
        icon: "path/to/sbi-logo.png",
      },
      {
        symbol: "LIFE INSURA CORP OF INDIA",
        price: "₹926.05",
        change: "-0.63%",
        volume: "353.24 K",
        marketCap: "₹5.9T",
        eps: "₹65.65",
        epsDilGrowth: "+5.91%",
        divYield: "1.07%",
        sector: "Finance",
        icon: "path/to/life-insura-logo.png",
      },
      {
        symbol: "ITC LTD",
        price: "₹468.85",
        change: "-0.24%",
        volume: "3.85 M",
        marketCap: "₹5.88T",
        eps: "₹16.42",
        epsDilGrowth: "+1.38%",
        divYield: "2.92%",
        sector: "Consumer non-durables",
        icon: "path/to/itc-logo.png",
      },
      {
        symbol: "HINDUSTAN UNILEVER LTD",
        price: "₹2,371.05",
        change: "-0.80%",
        volume: "359.15 K",
        marketCap: "₹5.4T",
        eps: "₹243.70",
        epsDilGrowth: "-0.16%",
        divYield: "1.80%",
        sector: "Consumer non-durables",
        icon: "path/to/hindustan-unilever-logo.png",
      },
      {
        symbol: "LARSEN & TOUBRO LTD",
        price: "₹3,868.65",
        change: "-0.47%",
        volume: "321.52 K",
        marketCap: "₹3.9T",
        eps: "₹101.79",
        epsDilGrowth: "+0.81%",
        divYield: "0.72%",
        sector: "Industrial services",
        icon: "path/to/larsen-toubro-logo.png",
      },
      {
        symbol: "HCL TECHNOLOGIES LTD",
        price: "₹1,621.75",
        change: "-0.31%",
        volume: "408.75 K",
        marketCap: "₹3.6T",
        eps: "₹62.02",
        epsDilGrowth: "+8.88%",
        divYield: "2.74%",
        sector: "Technology services",
        icon: "path/to/hcl-logo.png",
      },
      {
        symbol: "BAJAJ FINANCE LIMITED",
        price: "₹7,218.00",
        change: "+0.49%",
        volume: "378.77 K",
        marketCap: "₹4.45T",
        eps: "₹248.51",
        epsDilGrowth: "+15.04%",
        divYield: "0.50%",
        sector: "Finance",
        icon: "path/to/bajaj-finance-logo.png",
      },
      {
        symbol: "SUN PHARMACEUTICAL IND L",
        price: "₹1,794.90",
        change: "-1.02%",
        volume: "392.85 K",
        marketCap: "₹2.35T",
        eps: "₹246.07",
        epsDilGrowth: "+29.31%",
        divYield: "0.74%",
        sector: "Health technology",
        icon: "path/to/sun-pharma-logo.png",
      },
      {
        symbol: "MAHINDRA & MAHINDRA LTD.",
        price: "₹3,057.65",
        change: "-0.76%",
        volume: "875.84 K",
        marketCap: "₹2.6T",
        eps: "₹106.00",
        epsDilGrowth: "+6.13%",
        divYield: "0.68%",
        sector: "Consumer durables",
        icon: "path/to/mahindra-logo.png",
      },
      {
        symbol: "KOTAK MAHINDRA BANK LTD.",
        price: "₹1,797.65",
        change: "-0.44%",
        volume: "1.32 M",
        marketCap: "₹2.2T",
        eps: "₹110.94",
        epsDilGrowth: "+28.37%",
        divYield: "0.11%",
        sector: "Finance",
        icon: "path/to/kotak-mahindra-logo.png",
      },
      {
        symbol: "AXIS BANK LTD",
        price: "₹1,145.80",
        change: "-0.20%",
        volume: "1.03 M",
        marketCap: "₹2.12T",
        eps: "₹89.87",
        epsDilGrowth: "+113.11%",
        divYield: "0.09%",
        sector: "Finance",
        icon: "path/to/axis-bank-logo.png",
      },
      {
        symbol: "MARUTI SUZUKI INDIA LTD",
        price: "₹11,255.05",
        change: "-0.16%",
        volume: "78.58 K",
        marketCap: "₹3.5T",
        eps: "₹450.13",
        epsDilGrowth: "+19.78%",
        divYield: "1.11%",
        sector: "Consumer durables",
        icon: "path/to/maruti-suzuki-logo.png",
      },
      {
        symbol: "ULTRATECH CEMENT LTD",
        price: "₹11,930.70",
        change: "-1.27%",
        volume: "83.5 K",
        marketCap: "₹2.3T",
        eps: "₹227.17",
        epsDilGrowth: "+15.09%",
        divYield: "0.58%",
        sector: "Non-energy minerals",
        icon: "path/to/ultratech-cement-logo.png",
      },
      {
        symbol: "NTPC LTD.",
        price: "₹354.15",
        change: "-0.88%",
        volume: "160.57 K",
        marketCap: "₹1.56T",
        eps: "₹22.76",
        epsDilGrowth: "+15.41%",
        divYield: "2.24%",
        sector: "Utilities",
        icon: "path/to/ntpc-logo.png",
      },
  ];
  